# Site settings
title: Seafood Datasearch
email: your-email@example.com
description: >-
  Market analysis and forecasts for the seafood industry.

# GitHub Pages settings
baseurl: ""  # Leave empty for root deployment
url: "https://tobysackton.github.io"  # If using GitHub Pages

# If using a custom domain (like seafooddatasearch.com), replace with:
# url: "https://seafooddatasearch.com"

# Social media (optional)
twitter_username: ""
github_username: "tobysackton"

# Build settings
theme: minima
plugins:
  - jekyll-feed

# Ensure GitHub processes everything
include:
  - _pages
  - _layouts
  - _includes
  - assets

# Exclude unnecessary files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
